### PR TITLE
Fix Android compatibility problems

### PR DESCRIPTION
**Pull request by vladimir-poleh**
Added necessary permissions and APIs.
Now application will ask location permission for WiFi AP functionality.

### CODE REVIEW

**Comment by C-D-Lewis** [comment]
Wow, great work! Will review it very soon!

**Comment by C-D-Lewis** [comment]
Seems to restore functionality! 

My sincere thanks for your efforts, I could not have figured out half the new changes alone 🚀

**Comment by vladimir-poleh** [comment]
As I can see there are some problems with Dashboard work in the background. Will try to fix it on weekend.

**Comment by C-D-Lewis** [comment]
Please do. In any case, to unblock users (who are amazingly emailing me after all these years so some must still be out there), I will release tonight.

**Pull request merged**
